# Generated by Django 3.1.7 on 2021-03-02 16:57

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Busline',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='名稱')),
            ],
            options={
                'verbose_name_plural': '業務線',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='名稱')),
            ],
            options={
                'verbose_name_plural': '類型',
            },
        ),
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, verbose_name='資產編號')),
                ('remarks', models.TextField(blank=True, verbose_name='備註')),
                ('busline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.busline', verbose_name='業務線')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.category', verbose_name='類型')),
            ],
            options={
                'verbose_name_plural': '資產信息表',
            },
        ),
    ]
